apiVersion: v1
kind: Service
metadata:
  name: block-buster-service
  namespace: demo-1
  labels:
    app: block-buster
spec:
  type: NodePort
  selector:
    app: block-buster
    version: 7.1.0
    env: dev
  ports:
    - port: 80
      targetPort: 80      
